@test_call BoxStyle(LineStyle(Heavy), LineStyle(Light, Dashed1))
@test_opt BoxStyle(LineStyle(Heavy), LineStyle(Light, Dashed1))

bs = BoxStyle(LineStyle(Heavy), LineStyle(Light, Dashed1))
@test_call drawbox!(CANVAS1, (5, 5), 10, 5, bs)
@test_opt drawbox!(CANVAS1, (5, 5), 10, 5, bs)

reset!(CANVAS2)
drawbox!(CANVAS2, (1, 1), 10, 10, bs)
res = """
┎┄┄┄┄┄┄┄┄┒..........
┃........┃..........
┃........┃..........
┃........┃..........
┃........┃..........
┃........┃..........
┃........┃..........
┃........┃..........
┃........┃..........
┖┄┄┄┄┄┄┄┄┚..........
"""
test_canvas_output(CANVAS2, res)
