for lori in (Horizontal, Vertical)
    @test_call drawline!(CANVAS1, (1,1), 10, lori)
    @test_opt drawline!(CANVAS1, (1,1), 10, lori)
    for lsize in LSIZES, ltype in LTYPES
        lstyle = LineStyle(lsize, ltype)
        @test_call drawline!(CANVAS1, (1,1), 10, lori, lstyle)
        @test_opt drawline!(CANVAS1, (1,1), 10, lori, lstyle)
    end
end

reset!(CANVAS2)
drawline!(CANVAS2, (1, 1), 10, Horizontal)
res = """
──────────..........
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
ls = LineStyle(Heavy)
drawline!(CANVAS2, (1, 1), 10, Horizontal, ls)
res = """
━━━━━━━━━━..........
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
ls = LineStyle(Dashed1)
drawline!(CANVAS2, (1, 1), 10, Horizontal, ls)
res = """
┄┄┄┄┄┄┄┄┄┄..........
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawline!(CANVAS2, (1, 1), 10, Vertical)
res = """
│...................
│...................
│...................
│...................
│...................
│...................
│...................
│...................
│...................
│...................
"""
test_canvas_output(CANVAS2, res)
