for ldir in LDIRS, lsize in LSIZES
    es = EndStyle(NoEnd, ldir, LineStyle(lsize))
    @test_call drawend!(CANVAS1, (5, 5), es)
    @test_opt drawend!(CANVAS1, (5, 5), es)
    #@test_call drawend!(c, (5,5), EndStyle(ldir, LineStyle(lsize)))
    #@test_opt drawend!(c, (5,5), EndStyle(ldir, LineStyle(lsize)))
end
for lend in ARROWS, ldir in LDIRS
    es = EndStyle(lend, ldir, LineStyle())
    @test_call drawend!(CANVAS1, (5, 5), es)
    @test_opt drawend!(CANVAS1, (5, 5), es)
    #@test_call drawend!(c, (5,5), EndStyle(lend, ldir))
    #@test_opt drawend!(c, (5,5), EndStyle(lend, ldir))
end
for ldir in LDIRS, lsize in LSIZES
    es = EndStyle(Bar, ldir, LineStyle(lsize))
    @test_call drawend!(CANVAS1, (5, 5), es)
    @test_opt drawend!(CANVAS1, (5, 5), es)
end
for fchar in FREECHARS
    es = EndStyle(fchar, NoDirection, LineStyle())
    @test_call drawend!(CANVAS1, (5, 5), es)
    @test_opt drawend!(CANVAS1, (5, 5), es)
    #@test_call drawend!(c, (5,5), EndStyle(fchar))
    #@test_opt drawend!(c, (5,5), EndStyle(fchar))
end

paths = (
    ((1, 1), (5, 1), Vertical),
    ((1, 5), (1, 1), Vertical),
    ((1, 1), (1, 5), Vertical),
    ((5, 5), (1, 1), Vertical),
    ((1, 1), (5, 5), Vertical),
    ((1, 5), (5, 1), Vertical),
    ((5, 1), (1, 5), Vertical),
    ((1, 1), (1, 5), Horizontal),
    ((5, 1), (1, 1), Horizontal),
    ((1, 1), (5, 1), Horizontal),
    ((5, 5), (1, 1), Horizontal),
    ((1, 1), (5, 5), Horizontal),
    ((1, 5), (5, 1), Horizontal),
    ((5, 1), (1, 5), Horizontal),
    ((1, 1), 10, Vertical),
    ((1, 1), 10, Horizontal),
    ([(1, 1), (5, 5), (8, 10), (12, 6)], Vertical),
    ([(10, 10), (10, 5), (1, 5)], Vertical),
    ([(10, 10), (10, 5), (20, 5)], Vertical),
    ([(5, 1), (1, 5), (8, 10)], Vertical),
    ([(5, 1), (1, 10), (8, 5)], Vertical),
    ([(5, 1), (1, 5), (8, 5)], Vertical),
    ([(1, 1), (5, 10), (8, 10)], Vertical),
    ([(10, 1), (10, 10), (8, 1)], Vertical),
    ([(10, 1), (10, 2), (8, 10)], Vertical),
    ([(1, 1), (5, 5), (8, 10), (12, 6)], Horizontal),
    ([(10, 10), (10, 5), (1, 5)], Horizontal),
    ([(10, 10), (10, 5), (20, 5)], Horizontal),
    ([(1, 5), (20, 1), (20, 8)], Horizontal),
    ([(1, 1), (20, 10), (10, 8)], Horizontal),
    ([(1, 1), (20, 10), (20, 8)], Horizontal),
    ([(1, 1), (20, 1), (10, 8)], Horizontal),
    ([(1, 1), (10, 1), (20, 8)], Horizontal),
    ([(1, 1), (20, 1), (20, 8)], Horizontal),
    ([(1, 8), (20, 8), (20, 1)], Horizontal),
    ([(10, 1), (10, 3)], Vertical),
    ([(1, 8), (20, 8)], Horizontal),
    ([(1, 8)], Horizontal),
)

for p in paths
    lsize1, lsize2 = rand(LSIZES), rand(LSIZES)
    ltype1, ltype2 = rand(LTYPES), rand(LTYPES)
    lend1, lend2 = rand(LENDS), rand(LENDS)
    pstyle = PathStyle(LineStyle(lsize1, ltype1), LineStyle(lsize2, ltype2), lend1, lend2)
    @test_call drawpath!(CANVAS1, p..., pstyle)
    @test_opt drawpath!(CANVAS1, p..., pstyle)
end

reset!(CANVAS2)
drawpath!(CANVAS2, paths[1]..., PathStyle(Bar, BlackArrow))
res = """
├───▸...............
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[2]..., PathStyle(LineStyle(Heavy), BlackArrow))
res = """
▴...................
┃...................
┃...................
┃...................
▾...................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[3]..., PathStyle(LineStyle(Heavy), BlackRectangle, Lozenge))
res = """
▮...................
┃...................
┃...................
┃...................
◊...................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[4]..., PathStyle())
res = """
────┐...............
....│...............
....│...............
....│...............
....│...............
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[5]..., PathStyle(LineStyle(Light), LineStyle(Heavy), Bar, BlackArrow))
res = """
┬...................
│...................
│...................
│...................
┕━━━▸...............
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[6]..., PathStyle(Bar, BlackArrow))
res = """
┌───▸...............
│...................
│...................
│...................
┴...................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[7]..., PathStyle(Bar, BlackArrow))
res = """
....┬...............
....│...............
....│...............
....│...............
◂───┘...............
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[8]..., PathStyle(Bar, BlackArrow))
res = """
┬...................
│...................
│...................
│...................
▾...................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[9]..., PathStyle(Bar, BlackArrow))
res = """
◂───┤...............
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[10]..., PathStyle(Bar, BlackArrow))
res = """
├───▸...............
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[11]..., PathStyle(Bar, BlackArrow))
res = """
▴...................
│...................
│...................
│...................
└───┤...............
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[12]..., PathStyle(Bar, BlackArrow))
res = """
├───┐...............
....│...............
....│...............
....│...............
....▾...............
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[13]..., PathStyle(Bar, BlackArrow))
res = """
....▴...............
....│...............
....│...............
....│...............
├───┘...............
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[14]..., PathStyle(Bar, BlackArrow))
res = """
┌───┤...............
│...................
│...................
│...................
▾...................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[15]..., PathStyle(Bar, BlackArrow))
res = """
┬...................
│...................
│...................
│...................
│...................
│...................
│...................
│...................
│...................
▾...................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[16]..., PathStyle(Bar, BlackArrow))
res = """
├────────▸..........
....................
....................
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[17]..., PathStyle(Bar, BlackArrow))
res = """
┬...................
│...................
│...................
│...................
└───┐...............
....│..┌───▸........
....│..│............
....│..│............
....│..│............
....└──┘............
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[18]..., PathStyle(Bar, BlackArrow))
res = """
....................
....................
....................
....................
◂────────┐..........
.........│..........
.........│..........
.........│..........
.........│..........
.........┴..........
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[19]..., PathStyle(Bar, BlackArrow))
res = """
....................
....................
....................
....................
.........┌─────────▸
.........│..........
.........│..........
.........│..........
.........│..........
.........┴..........
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[20]..., PathStyle(Bar, BlackArrow))
res = """
....┬...............
....│...............
....│...............
....│...............
┌───┘...............
│...................
│...................
│...................
│...................
└──────▸............
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[21]..., PathStyle(Bar, BlackArrow))
res = """
....┬...............
....│...............
....│...............
....│...............
┌──────▸............
│...│...............
│...│...............
│...│...............
│...│...............
└───┘...............
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[22]..., PathStyle(Bar, BlackArrow))
res = """
....┬...............
....│...............
....│...............
....│...............
───────▸............
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[23]..., PathStyle(Bar, BlackArrow))
res = """
┬...................
│...................
│...................
│...................
│...................
│...................
│...................
│...................
│...................
└──────▸............
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[24]..., PathStyle(Bar, BlackArrow))
res = """
.......◂─┐..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[25]..., PathStyle(Bar, BlackArrow))
res = """
.........┬..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.......◂─┘..........
"""
test_canvas_output(CANVAS2, res)


reset!(CANVAS2)
drawpath!(CANVAS2, paths[26]..., PathStyle(Bar, BlackArrow))
res = """
├───┐...............
....│...............
....│...............
....│...............
....└──┐............
.......│...▴........
.......│...│........
.......│...│........
.......│...│........
.......└───┘........
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[27]..., PathStyle(Bar, BlackArrow))
res = """
....................
....................
....................
....................
◂────────┐..........
.........│..........
.........│..........
.........│..........
.........│..........
.........┴..........
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[28]..., PathStyle(Bar, BlackArrow))
res = """
....................
....................
....................
....................
.........┌─────────▸
.........│..........
.........│..........
.........│..........
.........│..........
.........┴..........
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[29]..., PathStyle(Bar, BlackArrow))
res = """
...................│
...................│
...................│
...................│
├──────────────────│
...................│
...................│
...................▾
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[30]..., PathStyle(Bar, BlackArrow))
res = """
├──────────────────┐
...................│
...................│
...................│
...................│
...................│
...................│
.........▴.........│
.........│.........│
.........└─────────┘
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[31]..., PathStyle(Bar, BlackArrow))
res = """
├──────────────────┐
...................│
...................│
...................│
...................│
...................│
...................│
...................▴
...................│
...................│
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[32]..., PathStyle(Bar, BlackArrow))
res = """
├────────┌──────────
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........│..........
.........▾..........
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[33]..., PathStyle(Bar, BlackArrow))
res = """
├──────────────────┐
...................│
...................│
...................│
...................│
...................│
...................│
...................▾
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[34]..., PathStyle(Bar, BlackArrow))
res = """
├──────────────────┐
...................│
...................│
...................│
...................│
...................│
...................│
...................▾
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[35]..., PathStyle(Bar, BlackArrow))
res = """
...................▴
...................│
...................│
...................│
...................│
...................│
...................│
├──────────────────┘
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[36]..., PathStyle(Bar, BlackArrow))
res = """
.........┬..........
.........│..........
.........▾..........
....................
....................
....................
....................
....................
....................
....................
"""
test_canvas_output(CANVAS2, res)

reset!(CANVAS2)
drawpath!(CANVAS2, paths[37]..., PathStyle(Bar, BlackArrow))
res = """
....................
....................
....................
....................
....................
....................
....................
├──────────────────▸
....................
....................
"""
test_canvas_output(CANVAS2, res)

@test_throws ErrorException drawpath!(CANVAS2, paths[38]..., PathStyle(Bar, BlackArrow))
