name = "Leonardo"
uuid = "6e51b308-25fb-4a35-ad5c-09aa117758e4"
authors = ["Arnold"]
version = "0.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"

[compat]
Crayons = "4.1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
